# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provision "shell", inline: <<-SHELL
    echo 'Install pip3'
    sudo apt-get update
    sudo apt-get -y install python3-pip
    pip3 install --upgrade pip

    echo 'Install python3 libraries'
    pip3 install \
      ipython \
      pipenv

  SHELL
  config.vm.network "forwarded_port", guest: 8081, host: 8081, host_ip: "127.0.0.1"
end
