# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.1.1"

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |v|
    v.name = "rancher"
    # keep memory high for stability
    v.memory = 4096
    v.cpus = 3
  end

  config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 443, host: 443, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 80, host: 80, host_ip: "127.0.0.1"
  
  # Install Rancher - https://rancher.com/
  config.vm.provision "docker" do |d|
    d.pull_images "rancher/rancher:latest"
    d.run "rancher",
      image: " rancher/rancher:latest",
      restart: "unless-stopped",
      args: "-p 80:80 -p 443:443 -v '/opt/rancher:/var/lib/rancher'"
  end

end
