# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "shell", inline: <<-SHELL
    export TERRAFORM_VERSION=0.12.4

    apt-get install unzip -y
    
    wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
    unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
    mv terraform /bin

    terraform -version
  SHELL

  config.vm.provision "shell", path: "../linux/ubuntu/install/awscli.sh"

  config.vm.network "private_network", type: "dhcp"
end