# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "terraform-sandbox" # show this name in virtualbox GUI
    vb.memory = 4048
    vb.cpus = 2
  end

  GITLAB_DOCKER_IMAGE = "gitlab/gitlab-ce:latest"

  config.vm.provision "shell", inline: <<-SHELL
    export TERRAFORM_VERSION=0.12.23

    apt-get install unzip -y
    
    wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
    unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
    mv terraform /bin

    terraform -version
  SHELL

  config.vm.provision "shell", path: "../linux/ubuntu/install/awscli.sh"
  config.vm.provision "docker"

  # GitLab - https://docs.gitlab.com/ee/ci/docker/using_docker_images.html
  config.vm.provision "docker" do |d|

    d.pull_images GITLAB_DOCKER_IMAGE
    d.run "gitlab",
      image: GITLAB_DOCKER_IMAGE,
      restart: "always",
      args: "-p 880:80 \
            -p 8443:443 \
            -v /srv/gitlab/config:/etc/gitlab \
            -v /srv/gitlab/logs:/var/log/gitlab \
             -v /srv/gitlab/data:/var/opt/gitlab"
  end

  config.vm.network "forwarded_port", guest: 880, host: 880
  config.vm.network "forwarded_port", guest: 8443, host: 8443

end