# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.1.1"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |v|
    v.name = "jenkins"
    # keep memory high for stability
    v.memory = 4096
    v.cpus = 3
  end

  config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 50000, host: 50000, host_ip: "127.0.0.1"
  config.vm.synced_folder ".", "/home/vagrant/jenkins"

  # Install containerized Jenkins 
  #   https://jenkins.io/doc/book/installing/#downloading-and-running-jenkins-in-docker
  #   https://www.vagrantup.com/docs/provisioning/docker.html#args-1
  config.vm.provision "docker" do |d|
    d.pull_images "jenkinsci/blueocean"
    d.run "jenkins",
      image: "jenkinsci/blueocean",
      # -m < 2GB crashes Jenkins`
      # docker.sock volume enables Jenkins to use local docker cli
      args: "-u root \
             -m 2GB \
             -p 8080:8080 -p 50000:50000 \
             -v 'jenkins-data:/var/jenkins_home' \
             -v '/var/run/docker.sock:/var/run/docker.sock'"
  end

  # use password for first login at localhost:8080
  config.vm.provision "shell", inline: <<-SHELL
    echo "Unlock Jenkins Password: $(docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword)"
  SHELL

end
