# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ansible-tower" # vagrant cli
  config.vm.box = "ansible/tower"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ansible-tower" # virtualbox GUI
  end

  config.vm.network "private_network", type: "dhcp"
end
