# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |v|
    v.name = "java"
    v.memory = 2048
  end

  config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 9000, host: 9000, host_ip: "127.0.0.1"

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update -y
    sudo yum install java -y
  SHELL

end